---
- name: Deploy Flask App to Jenkins
  hosts: jenkins-server
  become: yes

  tasks:
  - name: Install required packages
    package:
      name:
        - python3
        - python3-pip
        - git

  - name: Clone the Flask App repository
    git:
      repo: https://github.com/user/flask-app.git
      dest: /opt/flask-app

  - name: Install Flask and its dependencies
    pip:
      name: flask
      virtualenv: /opt/flask-env
      chdir: /opt/flask-app

  - name: Start the Flask App
    command: /opt/flask-env/bin/python3 /opt/flask-app/app.py
    async: 1
    poll: 0
    
    ...
